name: CI with Kubernetes

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: |
        docker build . -t rickandmorty-app:latest
        
    - name: Install kind
      run: |
        curl -Lo ./kind "https://kind.sigs.k8s.io/dl/v0.11.1/kind-$(uname)-amd64"
        chmod +x ./kind
        mv ./kind /usr/local/bin/kind
    
    - name: Create kind cluster
      run: |
        echo "kind: Cluster
        apiVersion: kind.x-k8s.io/v1alpha4
        nodes:
        - role: control-plane
        - role: worker" > kind-config.yaml
        kind create cluster --name kind --config kind-config.yaml

    - name: Load Docker image to kind
      run: |
        kind load docker-image rickandmorty-app:latest --name kind

    - name: Apply Kubernetes manifests
      run: |
        kubectl apply -f yamls/Deployment.yaml
        kubectl apply -f yamls/Service.yaml
        kubectl apply -f yamls/Ingress.yaml
        
    - name: Describe pods
      run: kubectl describe pods
    
    - name: Get events
      run: kubectl get events

    - name: Check deployment rollout status
      run: |
        kubectl rollout status deployment/rickandmorty-app

    - name: Test Application Endpoints
      run: |
        kubectl run curl --image=radial/busyboxplus:curl -i --tty --rm --restart=Never -- curl http://rickandmorty-app
        kubectl run curl --image=radial/busyboxplus:curl -i --tty --rm --restart=Never -- curl http://rickandmorty-app/api/characters
        kubectl run curl --image=radial/busyboxplus:curl -i --tty --rm --restart=Never -- curl http://rickandmorty-app/healthcheck
